[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[constraint]]
  branch = "master"
  name = "github.com/juju/errors"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/goproxy"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"
