name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: Cross build and publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installing Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Build cross
        run: make crosscompile
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: v${{ github.ref_name }}
          files: |
            ccbuilds/crawlera-headless-proxy-*

  push_to_registry:
    name: Push Docker image to Docker Hub
    strategy:
      matrix:
        include:
          - image: scrapinghub/crawlera-headless-proxy
            username: ${{ secrets.SCRAPINGHUB_DOCKER_USERNAME }}
            password: ${{ secrets.SCRAPINGHUB_DOCKER_USERNAME }}
          - image: zytedata/zyte-smartproxy-headless-proxy
            username: ${{ secrets.ZYTEDATA_DOCKER_USERNAME }}
            password: ${{ secrets.ZYTEDATA_DOCKER_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ matrix.username }}
          password: ${{ matrix.password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
